'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

<Assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000"),  _
 Assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2),  _
 Assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.0")> 

Namespace __ASP
    
    Friend Class FastObjectFactory_app_web_transactions_aspx_c99c6308_yuf2vwyy
        
        
        #ExternalSource("c:\\dummy.txt",1)

        #End ExternalSource
        
        
        Private Sub New()
            MyBase.New
        End Sub
        
        Shared Function Create_ASP_content_account_transactions_aspx() As Object
            Return New ASP.content_account_transactions_aspx()
        End Function
    End Class
End Namespace
